version: '3.4'

services:


  catalogdb:
    container_name: "catalogdb"
    ports:
     - "27017:27017" 
    volumes:
     - "mongo_data:/data/db"
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  orderdb:
    container_name: "orderdb"
    environment:
      ACCEPT_EULA : Y
      MSSQL_SA_PASSWORD: Impr0v1ng!
    ports:
      - 1433:1433   
  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcSettings__HostAddress=http://existance.grpc:5238
      - CacheSettings__ConnectionString=basketdb:6379
    ports:
      - "80"


  existance.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basketdb:
    container_name: basketdb
    ports:
      - 6379:6379
