version: '3.4'

services:
  
  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  orderdb:
    image: mcr.microsoft.com/mssql/server

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  existance.grpc:
    image: ${DOCKER_REGISTRY-}existancegrpc
    build:
      context: .
      dockerfile: Services/Existance/Existance.Grpc/Dockerfile
  
  basketdb:
    image: redis:alpine

volumes:
  mongo_data:



